### ISSUE TITLE
Migration Guide > v-for Array Refs の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#107]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/array-refs.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/array-refs.md

**Comment by daisuke85a** [comment]
@potato4d 
こちら翻訳させてください！ご検討をお願いいたします🙏

**Comment by egurinko** [comment]
@daisuke85a 
こちらありがとうございます 🙋 よろしくお願いいたします 🙇

**Comment by daisuke85a** [comment]
@egurinko 
割り当てありがとうございます！承知しました！
