### ISSUE TITLE
Migration Guide > Async Components の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#108]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/async-components.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/async-components.md

**Comment by u-sho** [comment]
@potato4d こちら担当してもよろしいでしょうか？

**Comment by potato4d** [comment]
@u-sho はい、お願いいたします！
