### ISSUE TITLE
Migration Guide > Custom Directives の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#110]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/custom-directives.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/custom-directives.md

**Comment by daisuke85a** [comment]
@potato4d @egurinko こちら担当したいですー！

**Comment by potato4d** [comment]
@daisuke85a ぜひ！お願いします！
