### ISSUE TITLE
Migration Guide > Custom Elements Interop の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#111]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/custom-elements-interop.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/custom-elements-interop.md

**Comment by kawamataryo** [comment]
@potato4d 

こちらの翻訳担当したいです!

**Comment by egurinko** [comment]
@kawamataryo 
こちらよろしくお願いいたします！
