### ISSUE TITLE
Migration Guide > Data Option の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#112]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/data-option.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/data-option.md

**Comment by nalpan** [comment]
@potato4d  こちら担当して良いでしょうか？

**Comment by potato4d** [comment]
@nalpan お願いします！
