### ISSUE TITLE
Migration Guide > Filters の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#114]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/filters.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/filters.md

**Comment by fuku710** [comment]
@potato4d こちら翻訳したいです！

**Comment by potato4d** [comment]
@fuku710 お願いします！
