### ISSUE TITLE
Migration Guide > Functional Components の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#116]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/functional-components.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/functional-components.md

**Comment by egurinko** [comment]
@jay-es 
こちらよろしくお願いいたします！ 🙇
