### ISSUE TITLE
Migration Guide > Global API の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#117]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/global-api.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/global-api.md

**Comment by bobstrange** [comment]
@potato4d @egurinko 

こちら翻訳担当させていただきたいです、よろしくお願いします :bow:

**Comment by egurinko** [comment]
@bobstrange 
こちらよろしくお願いいたします１
