### ISSUE TITLE
Migration Guide > Inline Template Attribute の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#119]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/inline-template-attribute.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/inline-template-attribute.md

**Comment by aytdm** [comment]
@potato4d @egurinko こちら翻訳します

**Comment by egurinko** [comment]
@aytdm 
ありがとうございます！こちらよろしくお願いいたします 🙇
