### ISSUE TITLE
Migration Guide > `key` attribute の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#120]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/key-attribute.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/key-attribute.md

**Comment by ryoAccount** [comment]
＠potato4d ＠egurinko
https://github.com/vuejs-jp/ja.vuejs.org/issues/1 でもコメントしましたが念のため…
こちらの翻訳を希望します。

**Comment by potato4d** [comment]
@ryoAccount よろしくお願いいたします！

**Comment by ryoAccount** [comment]
@potato4d @kazupon 
アサインいただいた後に気付いて恐縮ですが、
対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/key-attribute.md
が存在しません。

[key-attribute.html](https://v3.vuejs.org/guide/migration/key-attribute.html) を元に新規にmdを起こせばよろしいですか？

**Comment by ryoAccount** [comment]
memo

最新の本家にはあるが fork 時点での vuejs.org にはない。
本家のこちらを取り込んで翻訳する。
https://github.com/vuejs/docs-next/blob/master/src/guide/migration/key-attribute.md

https://vuejs-jp.slack.com/archives/C1P227P7V/p1603155441022200?thread_ts=1602944581.015500&cid=C1P227P7V
