### ISSUE TITLE
Migration Guide > KeyCode Modifiers の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#121]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/keycode-modifiers.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/keycode-modifiers.md

**Comment by shimadev** [comment]
@potato4d @egurinko 
こちら翻訳させていただきたいです！

**Comment by potato4d** [comment]
@shimadev よろしくお願いいたします！
