### ISSUE TITLE
Migration Guide > Props Default Function `this` Access の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#122]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/props-default-this.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/props-default-this.md

**Comment by daisuke85a** [comment]
@potato4d @egurinko 
こちら翻訳させていただきたいです！

**Comment by potato4d** [comment]
@daisuke85a 早速ありがとうございます！
