### ISSUE TITLE
Migration Guide > Render Function API の翻訳 

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#123]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/render-function-api.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/render-function-api.md

**Comment by resessh** [comment]
https://github.com/vuejs-jp/ja.vuejs.org/issues/1#issuecomment-711274737

**Comment by egurinko** [comment]
@resessh よろしくお願いいたします！
