### ISSUE TITLE
Migration Guide > Slots Unification の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#124]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/slots-unification.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/slots-unification.md

**Comment by Katakuranatsumi** [comment]
@potato4d 
こちら翻訳させていただきたいですmm

**Comment by potato4d** [comment]
@Katakuranatsumi お願いいたします！

**Comment by Katakuranatsumi** [comment]
@potato4d 
アサインありがとうございますmm
