### ISSUE TITLE
Migration Guide > Transition Class Change の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#125]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/transition.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/transition.md

**Comment by mmmommm** [comment]
@potato4d 
こちらの翻訳させていただきたいです。

**Comment by potato4d** [comment]
@mmmommm お願いします！
