### ISSUE TITLE
Migration Guide > v-model の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#126]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/v-model.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/v-model.md

**Comment by daisuke85a** [comment]
@potato4d 

お疲れ様です！
こちらの翻訳を担当させて頂きたいです！よろしくお願いします！

**Comment by potato4d** [comment]
#1 で声を上げていただいた @takumiz19 san にお願いします！

**Comment by daisuke85a** [comment]
@potato4d @takumiz19 こちら2週間経過したので巻き取ろうかとおもってますー！
