### ISSUE TITLE
Migration Guide > v-if vs. v-for Precedence の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#127]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/v-if-v-for.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/v-if-v-for.md

**Comment by unotovive** [comment]
こちら翻訳したいです！

**Comment by unotovive** [comment]
@potato4d こちら翻訳したいです！

**Comment by potato4d** [comment]
@unotovive よろしくお願いいたします！

**Comment by nalpan** [comment]
@potato4d @unotovive 
こちら巻き取らせて頂いてよいでしょうか？

**Comment by potato4d** [comment]
@nalpan はい、お願いします！

**Comment by potato4d** [comment]
こちら明日私の方でやってしまいます〜

**Comment by nalpan** [comment]
@potato4d 
oh...すみません、、、PR出したのですが不要であればcloseしてください

**Comment by potato4d** [comment]
@nalpan こちら取り込みました！ありがとうございますー！

**Comment by nalpan** [comment]
@potato4d 遅くなり申し訳無いです、ありがとうございます！🙇
