### ISSUE TITLE
Migration Guide > v-bind Merge Behavior の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#128]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/migration/v-bind.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/v-bind.md

**Comment by Shohei-Japan** [comment]
@potato4d @egurinko
こちらの翻訳を担当させていただきたいです。

**Comment by egurinko** [comment]
@Shohei-Japan 
こちらよろしくお願いいたします！ 🙇
