### ISSUE TITLE
Contribute to the Docs > Vue Docs Writing Guide の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#129]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/contributing/writing-guide.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/contributing/writing-guide.html

**Comment by nukopy** [comment]
@potato4d こちら，まだ asignee がいなければ翻訳を担当させていただきたいです．

**Comment by egurinko** [comment]
@nukopy 
ありがとうございます！こちらよろしくお願いいたします！

**Comment by nukopy** [comment]
@egurinko アサインありがとうございます！よろしくお願いします．
