### ISSUE TITLE
Contribute to the Docs > Documentation Style Guide の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#130]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/contributing/doc-style-guide.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/contributing/doc-style-guide.md

**Comment by potato4d** [comment]
重厚すぎるので分割します。
ここの希望はちょっとまってください 🙏

**Comment by potato4d** [comment]
こっちは違った 🙇 
この Issue は大丈夫です

**Comment by Katakuranatsumi** [comment]
@potato4d 
まだ空いていれば、こちらの翻訳をさせていただきたいですmm

**Comment by egurinko** [comment]
@Katakuranatsumi 
ありがとうございます！こちらよろしくお願いいたします 🙇

**Comment by Katakuranatsumi** [comment]
@egurinko 
アサインありがとうございますmm
