### ISSUE TITLE
Contribute to the Docs  > Translations の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#131]
This issue is a part of #1

## About

https://v3.vuejs.org/guide/contributing/translations.html の内容を翻訳いただきたいです。

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/contributing/translations.md

**Comment by tunamagur0** [comment]
@potato4d
こちら翻訳させていただきたいです!!

**Comment by egurinko** [comment]
@tunamagur0 
ありがとうございます！こちらよろしくお願いいたします 🙇
