### ISSUE TITLE
スタイルガイドの翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#138]
> #1 が終わったあとに募集しますが、先に声を上げてくださっても大丈夫です！
> ※ レビューの優先度が前後する可能性があります

## About

この Issue では、 https://v3.vuejs.org/style-guide/ の翻訳を目標として管理を進めます。

基本的に他の翻訳ガイドラインと同じルールで進行。スタイルガイドは内容が単体のページとしてはかなり多くなるため、プライオリティごとに分割して翻訳を募っています。

## Translation List

- [x] Style Guide 冒頭 / Rule Categories @t0yohei 
- [x] Priority A
- [x] Priority B
- [x] Priority C
- [x] Priority D

**Comment by t0yohei** [comment]
@potato4d @egurinko

> スタイルガイドは内容が単体のページとしてはかなり多くなるため、プライオリティごとに分割して翻訳を募っています。

`Translation List` にある項目ごとに翻訳の担当が割り当てられるイメージでしょうか？ 👀 
その場合、一番最初の `Style Guide 冒頭 / Rule Categories` を担当したいです！

**Comment by potato4d** [comment]
@t0yohei ですです！
お願いしますー！

**Comment by t0yohei** [comment]
@potato4d 
#158 でひとまず `Style Guide 冒頭 / Rule Categories` の翻訳プルリクエストを作成しました。
続けて、 `Priority A` の翻訳も担当したいです！

**Comment by potato4d** [comment]
@t0yohei ぜひぜひ！お願いします！

**Comment by daisuke85a** [comment]
@potato4d @egurinko 

Priority Bを担当させてもらえたら嬉しいです！

**Comment by kikd** [comment]
他にやっている方がいなければ、Priority Cの翻訳を担当したいです！

**Comment by potato4d** [comment]
@kikd ぜひ！お願いしますー！

**Comment by kis9a** [comment]
@potato4d @egurinko

他にやっている方がいなければ、Priority D の翻訳を担当させていただきたいです!
