### ISSUE TITLE
Components In-Depth > Slots の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#16]
Epic: #1

## About

https://v3.vuejs.org/guide/component-slots.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/component-slots.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by uiuifree** [comment]
@potato4d 
翻訳作業お手伝いさせてください〜

**Comment by potato4d** [comment]
@uiuifree
お願いいたします！

**Comment by potato4d** [comment]
@uiuifree 
こちらいかがでしょうか！お忙しそうであれば、私の方で翻訳いたします

**Comment by resessh** [comment]
@potato4d よければこちらやりたいです 🙏

**Comment by kazupon** [comment]
@resessh 
ありがとうございます！
@potato4d さんが問題ないなら、どうぞ、お願いします！

**Comment by potato4d** [comment]
@resessh ぜひ！お願いいたします！
