### ISSUE TITLE
Components In-Depth > Provide / inject  の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#17]
Epic: #1

## About

https://v3.vuejs.org/guide/component-provide-inject.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/component-provide-inject.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by mtmtkzm** [comment]
@potato4d こちら翻訳進めたいです 🙌

**Comment by potato4d** [comment]
よろしくお願いいたします！
