### ISSUE TITLE
Components In-Depth > Dynamic & Async Components  の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#18]
Epic: #1

## About

https://v3.vuejs.org/guide/component-dynamic-async.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/component-dynamic-async.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by resessh** [comment]
こちらやりたいです〜

**Comment by potato4d** [comment]
お願いします！
