### ISSUE TITLE
Introductionページ内に無効なリンクがある

### ISSUE THREAD

**Issue by Masa-Shin** [vuejs-jp/ja.vuejs.org#181]
[はじめに](https://v3.ja.vuejs.org/guide/introduction.html#vue-js-%E3%81%A8%E3%81%AF)の「Vue.jsとは」節の「他のフレームワークとの比較」のリンクが404になっていました。

<img width="743" alt="スクリーンショット 2020-12-12 20 27 52" src="https://user-images.githubusercontent.com/34234442/101982611-949e8d80-3cb8-11eb-9140-18a24db01b77.png">

英語版では[このcommit](https://github.com/vuejs-jp/ja.vuejs.org/commit/f558bf6da533a0d072af222d541d2cd9555ac91d#diff-f43200945b93eacb14613755322fd170adbc7ba5905b9349859b23245f80249b)で修正されていました。

対象ファイル：https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/introduction.md

**Comment by potato4d** [comment]
確認しますー

**Comment by potato4d** [comment]
こちら本日修正いたします 🙏

**Comment by naokie** [comment]
#272 で反映しましたので、こちらクローズします。
