### ISSUE TITLE
Components In-Depth > Template refs  の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#19]
Epic: #1

## About

https://v3.vuejs.org/guide/component-template-refs.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/component-template-refs.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by ushironoko** [comment]
@potato4d 
これやります

**Comment by potato4d** [comment]
@ushironoko お願いします
