### ISSUE TITLE
高度な使い方 はじめにページ スタンドアロンなcomputedプロパティに翻訳漏れがある。

### ISSUE THREAD

**Issue by manak1** [vuejs-jp/ja.vuejs.org#199]
高度な使い方はじめにページの[スタンドアロンな computed プロパティ](https://v3.ja.vuejs.org/guide/composition-api-introduction.html#watch-%E3%81%A6%E3%82%99%E5%A4%89%E5%8C%96%E3%81%AB%E5%8F%8D%E5%BF%9C%E3%81%99%E3%82%8B)セックションに翻訳漏れと思われる英文が残っていました。お手隙の際にご確認よろしくお願いします！

<img width="852" alt="スクリーンショット 2021-02-28 18 08 06" src="https://user-images.githubusercontent.com/32151765/109413298-fa650080-79ef-11eb-8f25-93a00515fbaa.png">

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/composition-api-introduction.md

**Comment by kazupon** [comment]
@manak1 ありがとうございます！近々、翻訳アップデートする予定があるので、そのとき対応します。
