### ISSUE TITLE
Migration > Attribute Coercion の翻訳

### ISSUE THREAD

**Issue by Shohei-Japan** [vuejs-jp/ja.vuejs.org#204]
This issue is a part of #201

# About
最後に日本語訳された時点より、master ブランチに変更が生じています。
該当ファイルの変更差分を確認していただき、翻訳をお願いいたします。

対象ページ
  - 英語ページ: https://v3.vuejs.org/guide/migration/attribute-coercion
  - 現状の日本語訳ページ: https://v3.ja.vuejs.org/guide/migration/attribute-coercion

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/attribute-coercion.md

**Comment by naokie** [comment]
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/attribute-coercion.md

前回からの差分
https://github.com/vuejs/docs-next/commit/639940b6154e318b0b26fd4a394defaa82eb45ba#diff-b479f35a5791f7d2ecdce48c7b3e621263cb53117bcf03bc2e7cf9a020974f49

表のマークダウンをフォーマットしたのみなので、翻訳の差分はなしとしてクローズして大丈夫みたいです。
