### ISSUE TITLE
Transitions & Animation > Overview の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#21]
Epic: #1

## About

https://v3.vuejs.org/guide/transitions-overview.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/transitions-overview.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by teruringo** [comment]
@potato4d こちらの #21 の翻訳希望です。よろしくお願いします。

**Comment by potato4d** [comment]
@teruringo お願いします

**Comment by potato4d** [comment]
@teruringo 
こちらいかがでしょうか！お忙しそうであれば、私の方で翻訳いたします！

**Comment by ryoAccount** [comment]
@potato4d 
問題なければ私の方で翻訳を担当させていただいてもよいですか？

**Comment by ryoAccount** [comment]
@potato4d 
問題なければ私の方で翻訳を担当させていただいてもよいですか？

**Comment by potato4d** [comment]
@ryoAccount 
ぜひぜひ！お願いいたします！

**Comment by ryoAccount** [comment]
アサインありがとうございます。着手します。
（来週中にPR出す目処感。）
