### ISSUE TITLE
Migration > Global Api Treeshaking の翻訳

### ISSUE THREAD

**Issue by Shohei-Japan** [vuejs-jp/ja.vuejs.org#215]
This issue is a part of #201

# About
最後に日本語訳された時点より、master ブランチに変更が生じています。
該当ファイルの変更差分を確認していただき、翻訳をお願いいたします。

対象ページ
  - 英語ページ: https://v3.vuejs.org/guide/migration/global-api-treeshaking
  - 現状の日本語訳ページ: https://v3.ja.vuejs.org/guide/migration/global-api-treeshaking

対象ファイル: https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/migration/global-api-treeshaking.md

**Comment by naokie** [comment]
ファイルの更新履歴
https://github.com/vuejs/docs-next/commits/master/src/guide/migration/global-api-treeshaking.md

前回からの差分
https://github.com/vuejs/docs-next/commit/c281bb8af3fe2bf74bde67e42c3fe6fe242aa230#diff-2817ca271fd5365e71d60136cee9b4ae5debca6f6aa09cfd0a0993ac130f24ff
https://github.com/vuejs/docs-next/commit/8cbc585fa06cb92b76a77da5a1162fd4c6290c47#diff-2817ca271fd5365e71d60136cee9b4ae5debca6f6aa09cfd0a0993ac130f24ff

英語としてのタイポや単語の重複など文法の修正なので、差分なしと取り扱って大丈夫そうです。
