### ISSUE TITLE
Transitions & Animation > Enter & Leave Transitions  の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#22]
Epic: #1

## About

https://v3.vuejs.org/guide/transitions-enterleave.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/transitions-enterleave.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by TakehiroTada** [comment]
@potato4d @vuejs-jp/contributers

こちらの #22 翻訳希望です、よろしくお願いいたします。

**Comment by potato4d** [comment]
@TakehiroTada お願いします！

**Comment by TakehiroTada** [comment]
@potato4d 
こちら、もう少し時間がかかっておりますので今しばらくお待ちくださいませ（最大で2日ほどでPR出します）

**Comment by potato4d** [comment]
@TakehiroTada  
こちらいかがでしょうか！お忙しそうであれば、私の方で翻訳いたします！

**Comment by potato4d** [comment]
こちら巻き取ります〜

**Comment by Katakuranatsumi** [comment]
@potato4d 
こちら、もしよろしければ着手しますmm

**Comment by potato4d** [comment]
@Katakuranatsumi 
すみません！こちら今既に進行中なので大丈夫ですー 🙇

**Comment by Katakuranatsumi** [comment]
@potato4d 
承知しましたmm
ご連絡ありがとうございます🙇‍♀️
