### ISSUE TITLE
Transitions & Animation > List Transitions   の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#23]
Epic: #1

## About

https://v3.vuejs.org/guide/transitions-list.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/transitions-list.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by hisako135** [comment]
こちら担当させて頂きたいです！ ✋

**Comment by potato4d** [comment]
@hisako135 お願いいたします！

**Comment by potato4d** [comment]
@hisako135 
こちらいかがでしょうか！お忙しそうであれば、私の方で翻訳いたします！

**Comment by potato4d** [comment]
こちら巻き取ります〜

**Comment by t0yohei** [comment]
@potato4d 
よろしければこちらの issue 担当したいです！

**Comment by potato4d** [comment]
@t0yohei 
すみません！こちら今既に進行中なので大丈夫ですー 🙇

**Comment by hisako135** [comment]
@potato4d 
コメント気付いておらず大変申し訳ありません！！
早くヘルプを出すべきでした。
本当に申し訳ありません。ありがとうございます。
