### ISSUE TITLE
Transitions & Animation > State Transitions の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#24]
Epic: #1

## About

https://v3.vuejs.org/guide/transitions-state.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/transitions-state.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by Shohei-Japan** [comment]
@potato4d @vuejs-jp/contributers
こちらの #24 Transitions & Animation > State Transitions の翻訳希望です。
よろしくお願いします。

**Comment by potato4d** [comment]
@Shohei-Japan よろしくお願いいたします！
