### ISSUE TITLE
Reusability & Composition > Custom Directives の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#26]
Epic: #1

## About

https://v3.vuejs.org/guide/custom-directive.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/custom-directive.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by mikakane** [comment]
@potato4d こちら翻訳担当希望です🤚

**Comment by potato4d** [comment]
@mikakane 表明ありがとうございます！
今 #14 にも参加表明いただいていると思いますので、そちらの完了の後にアサインさせていただければと思います。

**Comment by egurinko** [comment]
@potato4d 
こちらやりたいですん 🙋

**Comment by mikakane** [comment]
@potato4d 

すみません、一個づつなの把握してなかったです。
他にも手を上げてくださってる方いらっしゃるので、
@egurinko さんにお願いしたいと思います。

**Comment by potato4d** [comment]
@egurinko san お願いいたします！
