### ISSUE TITLE
Reusability & Composition > Teleport の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#27]
Epic: #1

## About

https://v3.vuejs.org/guide/teleport.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/teleport.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by potato4d** [comment]
@Pittan こちら、お願いいたします！

**Comment by resessh** [comment]
@potato4d こちらのissueはアサイン漏れですか…？アサインしてから外れた…？もしやる人いないようだったらやりたいです 🙏

**Comment by Pittan** [comment]
@resessh san, 
すみません、僕がAssignされているのですが 設定漏れでした 🙇 

@potato4d san, 
Contributorになっていないので、セルフアサインができませんでした。  
取り急ぎ
