### ISSUE TITLE
Reusability & Composition > Render Functions の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#28]
Epic: #1

## About

https://v3.vuejs.org/guide/render-function.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/render-function.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by wonderful-panda** [comment]
やります

**Comment by potato4d** [comment]
ありがとうございます！

**Comment by kazupon** [comment]
マージ済み。
