### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by skirtles-code** [vuejs-jp/ja.vuejs.org#284]
こんにちは

Sorry about my use of English.

I ran an internal link checker over the Japanese translation of the Vue 3 documentation. I've listed the broken links below. Hope it helps.

<details>
  <summary>Click for missing pages</summary>

* Missing page https://v3.ja.vuejs.org/guide/single-file-components.html
  - Linked from https://v3.ja.vuejs.org/style-guide/
* Missing page https://v3.ja.vuejs.org/api/options-api.html
  - Linked from https://v3.ja.vuejs.org/api/
* Missing page https://v3.ja.vuejs.org/api/reactivity-api.html
  - Linked from https://v3.ja.vuejs.org/api/
* Missing page https://v3.ja.vuejs.org/guide/'
  - Linked from https://v3.ja.vuejs.org/guide/component-attrs.html
* Missing page https://v3.ja.vuejs.org/guide/TODO
  - Linked from https://v3.ja.vuejs.org/guide/component-dynamic-async.html
* Missing page https://v3.ja.vuejs.org/guide/components.html
  - Linked from https://v3.ja.vuejs.org/guide/component-edge-cases.html
* Missing page https://v3.ja.vuejs.org/guide/transitions.html
  - Linked from https://v3.ja.vuejs.org/guide/transitions-state.html
* Missing page https://v3.ja.vuejs.org/guide/refs-api.html
  - Linked from https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html  
</details>

<details>
  <summary>Click for missing hashes</summary>

* Missing hash https://v3.ja.vuejs.org/style-guide/#テンプレート内でのコンポーネント名の形式-強く推奨
  - Linked from https://v3.ja.vuejs.org/style-guide/
* Missing hash https://v3.ja.vuejs.org/style-guide/#avoid-v-if-with-v-for-essential
  - Linked from https://v3.ja.vuejs.org/guide/conditional.html
  - Linked from https://v3.ja.vuejs.org/guide/list.html
  - Linked from https://v3.ja.vuejs.org/guide/list
* Missing hash https://v3.ja.vuejs.org/style-guide/#base-component-names-strongly-recommended
  - Linked from https://v3.ja.vuejs.org/guide/component-registration.html
* Missing hash https://v3.ja.vuejs.org/guide/migration/introduction.html#注目すべき新機能
  - Linked from https://v3.ja.vuejs.org/guide/migration/introduction.html
* Missing hash https://v3.ja.vuejs.org/guide/migration/introduction.html#サポートライブラリ
  - Linked from https://v3.ja.vuejs.org/guide/migration/introduction.html
* Missing hash https://v3.ja.vuejs.org/guide/contributing/translations.html#community-translations
  - Linked from all pages (in the main navigation)
* Missing hash https://v3.ja.vuejs.org/guide/installation.html#さまざまなビルドについて
  - Linked from https://v3.ja.vuejs.org/guide/installation.html
* Missing hash https://v3.ja.vuejs.org/guide/installation.html#explanation-of-different-builds
  - Linked from https://v3.ja.vuejs.org/guide/migration/global-api-treeshaking.html
* Missing hash https://v3.ja.vuejs.org/guide/instance.html#lifecycle-hooks
  - Linked from https://v3.ja.vuejs.org/guide/data-methods.html
* Missing hash https://v3.ja.vuejs.org/guide/instance.html#lifecycle-diagram
  - Linked from https://v3.ja.vuejs.org/api/application-api.html
  - Linked from https://v3.ja.vuejs.org/api/options-dom.html
  - Linked from https://v3.ja.vuejs.org/api/options-lifecycle-hooks.html
* Missing hash https://v3.ja.vuejs.org/guide/template-syntax.html#text
  - Linked from https://v3.ja.vuejs.org/api/directives.html
* Missing hash https://v3.ja.vuejs.org/guide/template-syntax.html#raw-html
  - Linked from https://v3.ja.vuejs.org/api/directives.html
* Missing hash https://v3.ja.vuejs.org/guide/computed.html#computed-properties
  - Linked from https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html
* Missing hash https://v3.ja.vuejs.org/guide/computed.html#watchers
  - Linked from https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html
  - Linked from https://v3.ja.vuejs.org/api/options-data.html
  - Linked from https://v3.ja.vuejs.org/api/instance-methods.html
* Missing hash https://v3.ja.vuejs.org/guide/list.html#maintaining-state
  - Linked from https://v3.ja.vuejs.org/guide/migration/key-attribute.html
* Missing hash https://v3.ja.vuejs.org/guide/list.html#displaying-filtered-sorted-results
  - Linked from https://v3.ja.vuejs.org/guide/migration/v-if-v-for.html
* Missing hash https://v3.ja.vuejs.org/guide/list.html#v-for-with-v-if
  - Linked from https://v3.ja.vuejs.org/guide/migration/v-if-v-for.html
  - Linked from https://v3.ja.vuejs.org/api/directives.html
* Missing hash https://v3.ja.vuejs.org/guide/events.html#イベント修飾子
  - Linked from https://v3.ja.vuejs.org/guide/template-syntax.html
* Missing hash https://v3.ja.vuejs.org/guide/forms.html#modifiers
  - Linked from https://v3.ja.vuejs.org/guide/component-custom-events.html
* Missing hash https://v3.ja.vuejs.org/guide/component-basics.html#passing-data-to-child-components-with-props
  - Linked from https://v3.ja.vuejs.org/guide/introduction.html
  - Linked from https://v3.ja.vuejs.org/api/directives.html
* Missing hash https://v3.ja.vuejs.org/guide/component-basics.html#using-v-model-on-components
  - Linked from https://v3.ja.vuejs.org/guide/forms.html
* Missing hash https://v3.ja.vuejs.org/guide/component-basics.html#dom-template-parsing-caveats
  - Linked from https://v3.ja.vuejs.org/guide/component-basics.html
  - Linked from https://v3.ja.vuejs.org/api/special-attributes.html
* Missing hash https://v3.ja.vuejs.org/guide/component-basics.html#content-distribution-with-slots
  - Linked from https://v3.ja.vuejs.org/api/options-dom.html
  - Linked from https://v3.ja.vuejs.org/api/instance-properties.html
  - Linked from https://v3.ja.vuejs.org/api/built-in-components.html
* Missing hash https://v3.ja.vuejs.org/guide/component-basics.html#keep-alive
  - Linked from https://v3.ja.vuejs.org/api/options-lifecycle-hooks.html
* Missing hash https://v3.ja.vuejs.org/guide/component-basics.html#emitting-a-value-with-an-event
  - Linked from https://v3.ja.vuejs.org/api/instance-methods.html
* Missing hash https://v3.ja.vuejs.org/guide/component-basics.html#listening-to-child-components-events
  - Linked from https://v3.ja.vuejs.org/api/directives.html
* Missing hash https://v3.ja.vuejs.org/guide/component-registration.html#local-registration
  - Linked from https://v3.ja.vuejs.org/guide/component-dynamic-async.html
  - Linked from https://v3.ja.vuejs.org/api/global-api.html
* Missing hash https://v3.ja.vuejs.org/guide/component-props.html#prop-validation
  - Linked from https://v3.ja.vuejs.org/style-guide/
  - Linked from https://v3.ja.vuejs.org/api/options-data.html
* Missing hash https://v3.ja.vuejs.org/guide/component-props.html#プロパティのバリデーション
  - Linked from https://v3.ja.vuejs.org/guide/component-props.html
  - Linked from https://v3.ja.vuejs.org/guide/component-props
* Missing hash https://v3.ja.vuejs.org/guide/component-props.html#prop-types
  - Linked from https://v3.ja.vuejs.org/api/options-data.html
* Missing hash https://v3.ja.vuejs.org/guide/component-props.html#disabling-attribute-inheritance
  - Linked from https://v3.ja.vuejs.org/api/options-misc.html
* Missing hash https://v3.ja.vuejs.org/guide/component-attrs.html#attribute-inheritance
  - Linked from https://v3.ja.vuejs.org/api/options-data.html
* Missing hash https://v3.ja.vuejs.org/guide/component-custom-events.html#validate-emitted-events
  - Linked from https://v3.ja.vuejs.org/guide/component-basics.html
* Missing hash https://v3.ja.vuejs.org/guide/component-custom-events.html#defining-custom-events
  - Linked from https://v3.ja.vuejs.org/guide/component-attrs.html
* Missing hash https://v3.ja.vuejs.org/guide/component-custom-events.html#v-model-arguments
  - Linked from https://v3.ja.vuejs.org/guide/component-custom-events.html
  - Linked from https://v3.ja.vuejs.org/api/directives.html
* Missing hash https://v3.ja.vuejs.org/guide/component-slots.html#デフォルトスロットしかない場合の省略記法
  - Linked from https://v3.ja.vuejs.org/guide/component-slots.html
* Missing hash https://v3.ja.vuejs.org/guide/component-slots.html#named-slots
  - Linked from https://v3.ja.vuejs.org/api/instance-properties.html
* Missing hash https://v3.ja.vuejs.org/guide/component-slots.html#destructuring-slot-props
  - Linked from https://v3.ja.vuejs.org/api/directives.html
* Missing hash https://v3.ja.vuejs.org/guide/component-slots.html#abbreviated-syntax-for-lone-default-slots
  - Linked from https://v3.ja.vuejs.org/api/directives.html
* Missing hash https://v3.ja.vuejs.org/guide/component-dynamic-async.html#動的コンポーネントにおける-keep-alive-の利用
  - Linked from https://v3.ja.vuejs.org/guide/migration/async-components.html
* Missing hash https://v3.ja.vuejs.org/guide/component-dynamic-async.html#async-components
  - Linked from https://v3.ja.vuejs.org/guide/migration/suspense.html
* Missing hash https://v3.ja.vuejs.org/guide/component-dynamic-async.html#dynamic-components-with-keep-alive
  - Linked from https://v3.ja.vuejs.org/api/built-in-components.html
* Missing hash https://v3.ja.vuejs.org/guide/component-template-refs.html#template-refs
  - Linked from https://v3.ja.vuejs.org/guide/migration/children.html
* Missing hash https://v3.ja.vuejs.org/guide/transitions-enterleave.html#JavaScript-フック
  - Linked from https://v3.ja.vuejs.org/guide/transitions-enterleave.html
  - Linked from https://v3.ja.vuejs.org/guide/transitions-enterleave
* Missing hash https://v3.ja.vuejs.org/guide/transitions-enterleave.html#コンポーネント間のトランジション
  - Linked from https://v3.ja.vuejs.org/guide/transitions-enterleave.html
  - Linked from https://v3.ja.vuejs.org/guide/transitions-enterleave
* Missing hash https://v3.ja.vuejs.org/guide/transitions-enterleave.html#transitioning-single-elements-components
  - Linked from https://v3.ja.vuejs.org/api/built-in-components.html
* Missing hash https://v3.ja.vuejs.org/guide/composition-api-setup.html#arguments
  - Linked from https://v3.ja.vuejs.org/guide/composition-api-introduction.html
* Missing hash https://v3.ja.vuejs.org/guide/composition-api-provide-inject.html#injection-reactivity
  - Linked from https://v3.ja.vuejs.org/guide/component-provide-inject.html
* Missing hash https://v3.ja.vuejs.org/guide/composition-api-template-refs.html#template-refs
  - Linked from https://v3.ja.vuejs.org/guide/component-template-refs.html
* Missing hash https://v3.ja.vuejs.org/guide/mixins.html#custom-option-merge-strategies
  - Linked from https://v3.ja.vuejs.org/api/application-config.html
* Missing hash https://v3.ja.vuejs.org/guide/mixins.html#global-mixin
  - Linked from https://v3.ja.vuejs.org/api/application-api.html
* Missing hash https://v3.ja.vuejs.org/guide/render-function.html#JSX
  - Linked from https://v3.ja.vuejs.org/style-guide/
* Missing hash https://v3.ja.vuejs.org/guide/render-function.html#Functional-Components
  - Linked from https://v3.ja.vuejs.org/guide/transitions-list.html
* Missing hash https://v3.ja.vuejs.org/guide/render-function.html#the-virtual-dom-tree
  - Linked from https://v3.ja.vuejs.org/guide/custom-directive.html
* Missing hash https://v3.ja.vuejs.org/guide/render-function.html#slots
  - Linked from https://v3.ja.vuejs.org/api/instance-properties.html
* Missing hash https://v3.ja.vuejs.org/guide/plugins.html#writing-a-plugin
  - Linked from https://v3.ja.vuejs.org/guide/plugins.html
* Missing hash https://v3.ja.vuejs.org/guide/reactivity-fundamentals.html#destructuring-reactive-state
  - Linked from https://v3.ja.vuejs.org/guide/composition-api-setup.html
* Missing hash https://v3.ja.vuejs.org/guide/reactivity-fundamentals.html#creating-standalone-reactive-values-as-refs
  - Linked from https://v3.ja.vuejs.org/guide/composition-api-provide-inject.html
  - Linked from https://v3.ja.vuejs.org/guide/composition-api-template-refs.html
  - Linked from https://v3.ja.vuejs.org/api/refs-api.html
* Missing hash https://v3.ja.vuejs.org/guide/reactivity-fundamentals.html#declaring-reactive-state
  - Linked from https://v3.ja.vuejs.org/guide/composition-api-provide-inject.html
  - Linked from https://v3.ja.vuejs.org/guide/state-management.html
* Missing hash https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html#stopping-the-watcher
  - Linked from https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html
  - Linked from https://v3.ja.vuejs.org/api/computed-watch-api.html
* Missing hash https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html#side-effect-invalidation
  - Linked from https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html
  - Linked from https://v3.ja.vuejs.org/api/computed-watch-api.html
* Missing hash https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html#effect-flush-timing
  - Linked from https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html
  - Linked from https://v3.ja.vuejs.org/api/computed-watch-api.html
* Missing hash https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html#watcher-debugging
  - Linked from https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html
  - Linked from https://v3.ja.vuejs.org/api/computed-watch-api.html
* Missing hash https://v3.ja.vuejs.org/guide/migration/custom-elements-interop.html#customized-built-in-elements
  - Linked from https://v3.ja.vuejs.org/guide/migration/introduction.html
* Missing hash https://v3.ja.vuejs.org/guide/migration/data-option.html#mixin-merge-behavior-change
  - Linked from https://v3.ja.vuejs.org/guide/migration/introduction.html
* Missing hash https://v3.ja.vuejs.org/guide/migration/fragments.html#overview
  - Linked from https://v3.ja.vuejs.org/guide/migration/custom-directives.html
* Missing hash https://v3.ja.vuejs.org/guide/migration/global-api.html#config-productiontip-removed
  - Linked from https://v3.ja.vuejs.org/guide/migration/global-api.html
* Missing hash https://v3.ja.vuejs.org/guide/migration/global-api.html#config-ignoredelements-is-now-config-iscustomelement
  - Linked from https://v3.ja.vuejs.org/guide/migration/global-api.html
* Missing hash https://v3.ja.vuejs.org/guide/migration/global-api.html#a-note-for-plugin-authors
  - Linked from https://v3.ja.vuejs.org/guide/migration/global-api.html
* Missing hash https://v3.ja.vuejs.org/guide/migration/global-api.html#vue-prototype-replaced-by-config-globalproperties
  - Linked from https://v3.ja.vuejs.org/guide/migration/global-api.html
* Missing hash https://v3.ja.vuejs.org/api/refs-api.html#access-in-templates
  - Linked from https://v3.ja.vuejs.org/guide/composition-api-setup.html
* Missing hash https://v3.ja.vuejs.org/guide/list#v-for-with-v-if
  - Linked from https://v3.ja.vuejs.org/guide/conditional.html
* Missing hash https://v3.ja.vuejs.org/guide/'#属性の継承
  - Linked from https://v3.ja.vuejs.org/guide/component-attrs.html
* Missing hash https://v3.ja.vuejs.org/guide/components.html#動的コンポーネント
  - Linked from https://v3.ja.vuejs.org/guide/transitions-enterleave.html
  - Linked from https://v3.ja.vuejs.org/guide/transitions-enterleave
* Missing hash https://v3.ja.vuejs.org/guide/transitions-enterleave#transition-modes
  - Linked from https://v3.ja.vuejs.org/guide/transitions-list.html
* Missing hash https://v3.ja.vuejs.org/guide/refs-api.html#ref
  - Linked from https://v3.ja.vuejs.org/guide/reactivity-computed-watchers.html
</details>

If you're curious, I wrote the checking tool myself. It's available at https://github.com/skirtles-code/vue-docs-link-checker. I don't doubt there are similar tools available elsewhere.

**Comment by kazupon** [comment]
@skirtles-code 
Thank you for your feedback!

Your link checker is great!
We can improve the documentation too.
Thank you once again!

**Comment by ytsujiii** [comment]
Click for missing pagesで指摘されている部分を修正したいと思っているのですが、取り掛かってみてもよろしいでしょうか？

**Comment by kazupon** [comment]
@ytsujiii 
ありがとうございます！
はい！助かります！

**Comment by ytsujiii** [comment]
missing pagesに対する修正PRを作りました！
よろしくお願い致します。

**Comment by naokie** [comment]
対応完了したためクローズします。
All fixed and closed.
