### ISSUE TITLE
Reusability & Composition > Plugins の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#29]
Epic: #1

## About

https://v3.vuejs.org/guide/plugins.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/plugins.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by potato4d** [comment]
@an-0305 よろしくお願いいたします！

**Comment by Shohei-Japan** [comment]
@potato4d @vuejs-jp/contributers
こちらの #29 Reusability & Composition > Plugins を翻訳希望です。
よろしくお願いします。

**Comment by potato4d** [comment]
@an-0305 こちら進行いただける認識で問題ありませんか？

**Comment by an-0305** [comment]
> @an-0305 こちら進行いただける認識で問題ありませんか？

はい、こちら進めさせていただきます
