### ISSUE TITLE
Essentials > Introduction の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#3]
Epic: #1

## About

https://v3.vuejs.org/guide/introduction.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/introduction.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by Shohei-Japan** [comment]
@potato4d @vuejs-jp/contributers
こちらの #3 Essentials > Introduction の担当がまだ決まっていなければ翻訳希望です。よろしくお願いします。

**Comment by potato4d** [comment]
@Shohei-Japan すみません、既に #1 にて @yh1224 san が声を上げていただいているので、別のセクションを依頼してもよろしいでしょうか 🙇‍♂️

**Comment by Shohei-Japan** [comment]
@potato4d 承知しました！
