### ISSUE TITLE
Advanced Guides > Compotion API > Introduction の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#32]
Epic: #1

## About

https://v3.vuejs.org/guide/composition-api-introduction.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/composition-api-introduction.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by egurinko** [comment]
@potato4d 
こちらちょいと長いですが翻訳希望です 🙋

**Comment by potato4d** [comment]
@egurinko 
すみません！ #1 で @saitoeku3 さんのほうで声が上がっていたのでお願いしてしまいました！
他のセクションでもよければ、ご協力いただければと思います 🙇‍♂️

**Comment by saitoeku3** [comment]
PR が遅れていますが、来週中には出せます！
ご迷惑をおかけして申し訳ありません🙏

**Comment by potato4d** [comment]
@saitoeku3 
こちら良ければ私の方で巻き取ります！

**Comment by saitoeku3** [comment]
@potato4d あと校正するだけなので本日中に PR を出します…！
