### ISSUE TITLE
Advanced Guides > Compotion API > Setup の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#33]
Epic: #1

## About

https://v3.vuejs.org/guide/composition-api-setup.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/composition-api-setup.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by tutti2612** [comment]
こちらの翻訳を担当したいです！

**Comment by tutti2612** [comment]
@potato4d 
こちらの翻訳ですが、@fuku710さんとバッティングしてしまいました。
どちらの担当になるのでしょうか？

**Comment by potato4d** [comment]
@tutti2612 san のほうが一時間早いと思うので、お願いしてもいいですか！
