### ISSUE TITLE
Advanced Guides > Compotion API > Lifecycle Hooks  の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#34]
Epic: #1

## About

https://v3.vuejs.org/guide/composition-api-Lifecycle-hooks.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/composition-api-Lifecycle-hooks.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by Skmt3P** [comment]
@potato4d ( @vuejs-jp/contributers )
担当者不在であれば担当させていただきますが、いかがでしょうか？

**Comment by mikakane** [comment]
@potato4d こちら翻訳させて頂きたく、ご連絡させています🤚

**Comment by potato4d** [comment]
@Skmt3P よろしくお願いいたします！

**Comment by Skmt3P** [comment]
@potato4d 承知しました。ガイドライン読んで適宜対応します！
