### ISSUE TITLE
Advanced Guides > Compotion API > Provide / Inject の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#35]
Epic: #1

## About

https://v3.vuejs.org/guide/composition-api-Provide-Inject.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/composition-api-Provide-Inject.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by bobstrange** [comment]
@potato4d 
こちら翻訳担当希望します :bow:

**Comment by potato4d** [comment]
@bobstrange
ありがとうございます！よろしくお願いいたします！
