### ISSUE TITLE
The description of `this` in setup is inconsistent with the source code

### ISSUE THREAD

**Issue by naokie** [vuejs-jp/ja.vuejs.org#368]
New updates on head repo.
https://github.com/vuejs/docs-next/commit/42bb2a2abf2a93f30094cf645e433b5ffca2744a

**Comment by kazupon** [comment]
chetsumi-next 、バグった？

**Comment by naokie** [comment]
oh...

https://github.com/vuejs-jp/che-tsumi-next/blob/42ed6f259582a3bfacbc23e0079a807e6fb14d14/src/chetsumi.ts#L125
Issue 作るときに利用している文字列が、Feed のコンテンツ、つまりコミットメッセージ全文になっちゃってました。

ここは `feed.title` がよさそう。
vite-docs-ja でも同じ現象起きてましたが、コミットメッセージが短いからか、気づいてなかったですね 😅
