### ISSUE TITLE
Render Mechanisms > Rendering Mechanisms and Optimizations の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#37]
Epic: #1

## About

https://v3.vuejs.org/guide/optimizations.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/optimizations.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by potato4d** [comment]
@y-temp4 よろしくお願いいたします！

**Comment by y-temp4** [comment]
@potato4d すみません、自分自身の issue へのアサインなのですが、どうやらこちらのほうでできないっぽいので、お手すきの際に割り当てていただけますと幸いです🙏

**Comment by potato4d** [comment]
@y-temp4 Done 🙏

**Comment by y-temp4** [comment]
@potato4d ありがとうございます！
