### ISSUE TITLE
add migration/migration-build.md

### ISSUE THREAD

**Issue by t0yohei** [vuejs-jp/ja.vuejs.org#379]
下記プルリクエストで migration build についてのページと、そのページへのリンクが追加されました
https://github.com/vuejs/docs-next/pull/1033

migration build についてのページは以下。
https://v3.vuejs.org/guide/migration/migration-build.html#overview

**Comment by kazupon** [comment]
ご指摘ありがとうございます！
はい、こちらも今後翻訳対象にしていきますね！

**Comment by t0yohei** [comment]
もしよかったらこちらの翻訳担当させていただけないでしょうか？ 👀

**Comment by kazupon** [comment]
@t0yohei 
Welcomeです！助かります！

/cc @naokie

**Comment by naokie** [comment]
わ、翻訳担当していただけるのは、正直助かります！！
ぜひお願いします 🙏🏼

**Comment by t0yohei** [comment]
@naokie @kazupon 
遅くなってしまいすいません、プルリクエストを作成しましたのでレビューよろしくお願いします 🙇

**Comment by kazupon** [comment]
@t0yohei 
ありがとうございます！
すいません、明日オンラインイベントの準備等あるので、終わったらレビューしますね。
