### ISSUE TITLE
Render Mechanisms > Change Detection Caveats in Vue 2 の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#38]
Epic: #1

## About

https://v3.vuejs.org/guide/change-detection.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/change-detection.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by Katakuranatsumi** [comment]
@potato4d 
こちらの翻訳を希望しますmm

**Comment by potato4d** [comment]
@Katakuranatsumi よろしくお願いいたします！

**Comment by Katakuranatsumi** [comment]
@potato4d 
アサインありがとうございますmm
