### ISSUE TITLE
Scaling Up > Routing の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#42]
Epic: #1

## About

https://v3.vuejs.org/guide/routing.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/routing.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by potato4d** [comment]
@bake0937
こちら、お願いいたします！

**Comment by bake0937** [comment]
@potato4d `Outside Collaborator (Read) `の招待メールに先程気付いて`View invitation`しました．申し訳ございません．
問題なければ(`Outside Collaborator (Read)`として私が追加されていたら)，このIssueの`Assignees`に私を指定して頂けると幸いです．
翻訳のPRは先程作成しました．
