### ISSUE TITLE
Scaling Up > State Management の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#43]
Epic: #1

## About

https://v3.vuejs.org/guide/state-management.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/state-management.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by potato4d** [comment]
@YukiOta
お願いします！

**Comment by YukiOta** [comment]
@potato4d 
ありがとうございます！
こちら Outside Collaborator の招待頂いてますかね...?
