### ISSUE TITLE
Scaling Up > Server-Side Rendering の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#44]
Epic: #1

## About

https://v3.vuejs.org/guide/ssr.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/ssr.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by potato4d** [comment]
@krabben16
お願いいたします！

**Comment by krabben16** [comment]
@potato4d 
#1 の [コメント](https://github.com/vuejs-jp/ja.vuejs.org/issues/1#issuecomment-693386423) に👀が付いているのですが
他のセクションを担当したほうがよろしいでしょうか？
それともこちらのイシューは私にアサイン済でしょうか？

**Comment by potato4d** [comment]
@krabben16 アサイン済みで大丈夫です！
