### ISSUE TITLE
Accessibility > Basic の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#45]
Epic: #1

## About

https://v3.vuejs.org/guide/a11y-basics.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/a11y-basics.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by ryo-gk** [comment]
@potato4d 
こちらの翻訳を担当させていただきたいです。

**Comment by potato4d** [comment]
@ryo-gk 
すみません！ #1 で @yamanoku さんが先に声を上げていただいたので、他のあきのセクションをお願いしてもよろしいでしょうか 🙇‍♂️
