### ISSUE TITLE
Accessibility > Semantics の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#46]
Epic: #1

## About

https://v3.vuejs.org/guide/a11y-semantics.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/a11y-semantics.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by ryo-gk** [comment]
@potato4d 
こちらの担当をさせてください！

**Comment by potato4d** [comment]
@ryo-gk よろしくお願いいたします！

**Comment by potato4d** [comment]
@sunecosuri 先に ryo-gk san に声を上げていただいたので、他のセクションを依頼してもよろしいでしょうか…… 🙇‍♂️
