### ISSUE TITLE
タイポの修正

### ISSUE THREAD

**Issue by obregonia1** [vuejs-jp/ja.vuejs.org#469]
一箇所タイポしている部分がありましたので修正お願いします。
https://v3.ja.vuejs.org/guide/component-provide-inject.html#%E3%83%AA%E3%82%A2%E3%82%AF%E3%83%86%E3%82%A3%E3%83%95%E3%82%99%E3%81%A8%E9%80%A3%E6%90%BA%E3%81%99%E3%82%8B
- リアクティブと連携するの項目
    - 誤: computed で定義したプロパティを todoLength を割り当てる
    - 正: computed で定義したプロパティtodoLength を割り当てる

**Comment by naokie** [comment]
タイポの報告ありがとうございます！
近日中に修正しますね。

**Comment by obregonia1** [comment]
ありがとうございます！
