### ISSUE TITLE
Accessibility > Standards の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#47]
Epic: #1

## About

https://v3.vuejs.org/guide/a11y-standards.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/a11y-standards.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by ryoAccount** [comment]
＠potato4d 
https://github.com/vuejs-jp/ja.vuejs.org/issues/1#issuecomment-693634672 でコメントしましたが、念のためここにもコメント入れておきます。

**Comment by potato4d** [comment]
@ryoAccount お願いします！
