### ISSUE TITLE
template-syntax.md について、修正の提案

### ISSUE THREAD

**Issue by tarohida** [vuejs-jp/ja.vuejs.org#470]
## 内容

> ここでの引数は受け取りたいイベント名です。ここからイベントハンドリングの詳細について説明します。

の箇所について、

> ここでの引数は受け取りたいイベント名です。イベントハンドリングの詳細については後ほど説明します。

のような形の方が適切かと感じました。いかがでしょうか？

英語版

> Here the argument is the event name to listen to. We will talk about event handling in more detail too.

## リンク

日本語訳の該当箇所：https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/template-syntax.md#%E5%BC%95%E6%95%B0
英語版の該当箇所：https://v3.vuejs.org/guide/template-syntax.html#arguments

---

Vue3.x の日本語ドキュメントについて、順に読ませていただいています。翻訳いただきありがとうございます。

**Comment by naokie** [comment]
提案ありがとうございます！
原文とは違い、意訳になっていますね。
日本語としても、直後から説明が始まっているわけではなく、少し不自然と感じられるものなので修正しますね。

よかったら PR までしていただけると、もっと修正早くできますよ！

**Comment by tarohida** [comment]
ありがとうございます、修正してみたいです。
今月中めどくらいのペースになると思いますが、 PR 出します。

**Comment by tarohida** [comment]
@naokie 
質問です。CONTRIBUTING.md の下記手順がわからなかったのですが、今回のような修正では関係ないものでしょうか？

1. 翻訳した `.md` の `updated` 属性を修正した日に変更してコミットします: `git commit -am 'Update date'`

**Comment by naokie** [comment]
さっそく修正作業ありがとうございます！
質問してもらった箇所ですが、ちょっと自分もこれはどういった意図のものかわからないので、消しておきますね。
今回は無視してもらって大丈夫です。

**Comment by tarohida** [comment]
ありがとうございます。PR提出しておきました。
