### ISSUE TITLE
Essentials > Computed Properties and Watchers の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#49]
Epic: #1

## About

https://v3.vuejs.org/guide/computed.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/computed.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by jay-es** [comment]
@potato4d @vuejs-jp/contributers
こちらの #49 Essentials > Computed Properties and Watchers を翻訳希望です。
よろしくお願いします。

**Comment by potato4d** [comment]
はい！よろしくお願いいたします！
