### ISSUE TITLE
日本語での検索がうまくいかない

### ISSUE THREAD

**Issue by willnet** [vuejs-jp/ja.vuejs.org#493]
画面右上の検索フォームから日本語を入力してもなにも結果が出てきません。

![image](https://user-images.githubusercontent.com/82371/130404226-50a8f946-9a93-4b3e-b7dc-0d3cc3e06852.png)

英語を入力すると結果が出てきます。リンクをクリックすると日本語版のインストールのページに飛びます ( https://v3.ja.vuejs.org/guide/installation.html#installation )

![image](https://user-images.githubusercontent.com/82371/130404315-76ea4f2d-ff49-4985-ac21-708c2225dbb3.png)

algoliaのインデックス設定がおかしいのかな？と思いましたがそのへんよくわからないのでIssueで共有だけしておきます。

**Comment by kazupon** [comment]
ご報告ありがとうございます！
確かに検索されていないようです...

vuepress.config.js 確認したところ、本家のままのようです...
https://github.com/vuejs-jp/ja.vuejs.org/blob/6f7b925e59db654cd70e6249faea7a5ab0765a52/src/.vuepress/config.js#L502-L506

docsearch-configs で日本語向けにチューニングする必要がありますね。
https://github.com/algolia/docsearch-configs

/ping @naokie /cc @kiaking

**Comment by kazupon** [comment]
こちら対応させていただきますので、少々お待ちを 🙇

**Comment by naokie** [comment]
すごく昔に話題にあがっていたのを、どこかで見かけた記憶がありますね。
その時は特に対応の検討なされずにコメントアウトしていたのを、どこかのタイミングでもどしちゃったようです 🙇🏼 

それで中国語の方を見てきました。
各コミュニティでそれぞれインデックスを生成するような管理？になるのかなと想像してるのですが。
https://github.com/vuejs/docs-next-zh-cn/blob/master/src/.vuepress/config.js#L509-L512

一方でロシア語は別途管理必要になるからか、コメントアウトしていますね。
https://github.com/translation-gang/docs-next/blob/master/src/.vuepress/config.js#L563-L567

グローバルでどういった方針とるかなど、本家との議題にあげてもらってもよいですか？

**Comment by kazupon** [comment]
@naokie 
各国のドキュメントの確認ありがとうございます！
そうですね、一旦確認はしておきます。

algolia の docsearch はドメインをベースに index していくので、
日本は日本で、docsearch-confg に index されるようにすれば、いけると思います。

中国サイドの対応commit履歴は、こちらですね。
https://github.com/algolia/docsearch-configs/search?q=vuejs_cn3&type=commits
