### ISSUE TITLE
GitHub の OGP を作りたい

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#51]
@448jp san が作ったりしてくれないかな……というちょっとした願いです

**Comment by potato4d** [comment]
[![Image from Gyazo](https://i.gyazo.com/a5e89b8f1b14759d815dddaa2de3d67a.png)](https://gyazo.com/a5e89b8f1b14759d815dddaa2de3d67a)

**Comment by 448jp** [comment]
@potato4d 
やりましょう！（ちと仕事が立て込んでいるので、10月以降になりそうです

**Comment by 448jp** [comment]
@kazupon @potato4d 
大変遅くなりましたが作ってみました。
![image](https://user-images.githubusercontent.com/1371326/104226433-23a2ef00-548b-11eb-8b4b-6f8d9df4b80e.png)

- Vue.js日本ユーザーグループのロゴを入れましたが、ユーザーグループ主導のリポジトリというわけではないのでVue.js公式ロゴ（Vだけのもの）の方がいいでしょうか？
    - これはこれで日本が関連しているものと分かりやすいのでいいかなーとも思っております
- 基本的には日本語が分かる人を対象としたリポジトリなので、「Vue 3 公式日本語ウェブサイトリポジトリ」というタイトルを設けてみました
    - 英語の方がよい？この文言がよいか？はご意見いただきたいです

というわけでこれをたたき台に調整できればとー。

**Comment by kazupon** [comment]
@448jp 
お忙しいところ、本当にありがとうございます！ 

> Vue.js日本ユーザーグループのロゴを入れましたが、ユーザーグループ主導のリポジトリというわけではないのでVue.js公式ロゴ（Vだけのもの）の方がいいでしょうか？
> * これはこれで日本が関連しているものと分かりやすいのでいいかなーとも思っております

ロゴについては、デザインしていただいた今の案でいいかなと思っています。
v3以前は、vuejs org 配下で翻訳、メンテナンスしていましたが、v3 以降は、vuejs-jp org 配下で **Vue.js 公式の翻訳ドキュメント**となっています。今後は**ユーザーグループ運営の元で関わりながら、日本のコミュニティの方々が翻訳、メンテナンスしていく形にしたい**と思っています。

Vue.js公式、ユーザーグループグループ、それぞれが入っているので、ロゴデザインは、今回して頂いた案に合うのでいいと思っています。

> 基本的には日本語が分かる人を対象としたリポジトリなので、「Vue 3 公式日本語ウェブサイトリポジトリ」というタイトルを設けてみました
> * 英語の方がよい？この文言がよいか？はご意見いただきたいです

ウェブサイトはというよりは、ドキュメントサイトですかね。ひたすら解説しているものが乗っているサイトなので。
リポジトリはあえて強調しなくても「Vue 3 公式日本語ドキュメント」でもいい気がしています。

**Comment by 448jp** [comment]
@kazupon 
とんでもないですー、だいぶおまたせしてしまってすみません。文言だけ修正したものをアップします。
![image](https://user-images.githubusercontent.com/1371326/104411750-54c81000-55ae-11eb-9966-39c56634f359.png)

**Comment by potato4d** [comment]
@448jp 
めっちゃ良いです……！

**Comment by kazupon** [comment]
@potato4d さんも最後にアップされた案でよさそうなので、それでいきましょう！
OGP の設定お願します！ :pray:

**Comment by kazupon** [comment]
OGP設定しました。
![image](https://user-images.githubusercontent.com/72989/108078932-95d1a980-70b1-11eb-8759-5bdbe5922f74.png)

@448jp さんありがとうございました！
