### ISSUE TITLE
置換されるコンテンツの説明と例が少し違う

### ISSUE THREAD

**Issue by selvarajmas** [vuejs-jp/ja.vuejs.org#584]
細かいことになりますが、
置換されるコンテンツの説明と例が少し違う

説明：「Add Todo」に置換されるでしょう
例　：「Add todo」に置換されている      

＜対象ページ＞
https://v3.ja.vuejs.org/guide/component-slots.html#%E3%82%B9%E3%83%AD%E3%83%83%E3%83%88%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84

![image](https://user-images.githubusercontent.com/22630424/143328398-718bb5f5-f0ae-4d4b-acf2-2d8f145cd4d2.png)

**Comment by naokie** [comment]
resolved with #585
