### ISSUE TITLE
リンクを押した後、適切な場所に遷移されない

### ISSUE THREAD

**Issue by selvarajmas** [vuejs-jp/ja.vuejs.org#586]
下記のリンクを押した後、適切な場所に遷移されないので
リンクの修正が必要です。

＜対象リンク＞
・後で説明しますが
場所：インストール → 自分でホストする → 「後で説明しますが」のリンク
[参照](https://v3.ja.vuejs.org/guide/installation.html#%E8%87%AA%E5%88%86%E3%81%A6%E3%82%99%E3%83%9B%E3%82%B9%E3%83%88%E3%81%99%E3%82%8B)

・検証する
場所：コンポーネントの基本 → 子コンポーネントのイベントを購読する → 「検証する」のリンク
[参照](https://v3.ja.vuejs.org/guide/component-basics.html#%E5%AD%90%E3%82%B3%E3%83%B3%E3%83%9B%E3%82%9A%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%81%AE%E3%82%A4%E3%83%98%E3%82%99%E3%83%B3%E3%83%88%E3%82%92%E8%B3%BC%E8%AA%AD%E3%81%99%E3%82%8B)

・DOM テンプレートの構文解析の注意点
場所：コンポーネントの基本 → コンポーネントで v-model を使う → WARNING部分の「DOM テンプレートの構文解析の注意点」のリンク
[参照](https://v3.ja.vuejs.org/guide/component-basics.html#%E3%82%B3%E3%83%B3%E3%83%9B%E3%82%9A%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%81%A6%E3%82%99-v-model-%E3%82%92%E4%BD%BF%E3%81%86)

・ライフサイクルフック
場所：データプロパティとメソッド → メソッド → 「ライフサイクルフック」のリンク
[参照](https://v3.ja.vuejs.org/guide/data-methods.html#%E3%83%A1%E3%82%BD%E3%83%83%E3%83%88%E3%82%99)

・プロパティのバリデーション
場所：プロパティ → プロパティの型 → 「プロパティのバリデーション」のリンク
[参照](https://v3.ja.vuejs.org/guide/component-props.html#%E3%83%95%E3%82%9A%E3%83%AD%E3%83%8F%E3%82%9A%E3%83%86%E3%82%A3%E3%81%AE%E5%9E%8B)

・関数型コンポーネント
場所：リストのトランジション → 再利用可能なトランジション → 「関数型コンポーネント」のリンク
[参照](https://v3.ja.vuejs.org/guide/transitions-list.html#%E5%86%8D%E5%88%A9%E7%94%A8%E5%8F%AF%E8%83%BD%E3%81%AA%E3%83%88%E3%83%A9%E3%83%B3%E3%82%B7%E3%82%99%E3%82%B7%E3%83%A7%E3%83%B3)

・サポートライブラリ
場所：Vue 2 から移行 → はじめに → 「サポートライブラリ」のリンク
[参照](https://v3.ja.vuejs.org/guide/migration/introduction.html#%E3%81%AF%E3%81%97%E3%82%99%E3%82%81%E3%81%AB)

・Composition API のセクション
場所：Provide / inject　→　リアクティブと連携する → 「Composition API のセクション」のリンク
[参照](https://v3.ja.vuejs.org/guide/component-provide-inject.html#%E3%83%AA%E3%82%A2%E3%82%AF%E3%83%86%E3%82%A3%E3%83%95%E3%82%99%E3%81%A8%E9%80%A3%E6%90%BA%E3%81%99%E3%82%8B)

・API リファレンス
場所：動的 & 非同期コンポーネント　→　Suspense との併用　→　「API リファレンス」のリンク
[参照](https://v3.ja.vuejs.org/guide/component-dynamic-async.html#suspense-%E3%81%A8%E3%81%AE%E4%BD%B5%E7%94%A8)

・ES2015 の分割代入
場所：スロット　→　スロットプロパティの分割代入　→　「ES2015 の分割代入」のリンク
[参照](https://v3.ja.vuejs.org/guide/component-slots.html#%E3%82%B9%E3%83%AD%E3%83%83%E3%83%88%E3%83%95%E3%82%9A%E3%83%AD%E3%83%8F%E3%82%9A%E3%83%86%E3%82%A3%E3%81%AE%E5%88%86%E5%89%B2%E4%BB%A3%E5%85%A5)

**Comment by naokie** [comment]
resolved with #587
