### ISSUE TITLE
forms.md について修正の提案

### ISSUE THREAD

**Issue by tojimasan** [vuejs-jp/ja.vuejs.org#632]
## 内容
```
<!-- toggle` は true または false のどちらかです -->
```

の表記についてですが、英語版に併せて

```
<!-- `toggle` は true または false のどちらかです -->
```

のような形の方が適切かと感じました。いかがでしょうか？

英語版

```
<!-- `toggle` is either true or false -->
```

## リンク
日本語訳の該当箇所：https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/forms.md#:~:text=%3C!%2D%2D%20toggle%60%20%E3%81%AF%20true%20%E3%81%BE%E3%81%9F%E3%81%AF%20false%20%E3%81%AE%E3%81%A9%E3%81%A1%E3%82%89%E3%81%8B%E3%81%A7%E3%81%99%20%2D%2D%3E
英語版の該当箇所：https://vuejs.org/guide/essentials/forms.html#:~:text=%3C!%2D%2D%20%60toggle%60%20is%20either%20true%20or%20false%20%2D%2D%3E

Vue3.x の日本語ドキュメントを参考に勉強させていただいております。

**Comment by naokie** [comment]
@tojimasan 
指摘いただいて、ありがとうございます！
たしかに抜けていましたね 😅 

d00f33803c7bd6e6dfd10ed5d391981cf0186e7a
こちらのコミットで修正しました。
