### ISSUE TITLE
このプロジェクトは維持されていますか?

### ISSUE THREAD

**Issue by ghost** [vuejs-jp/ja.vuejs.org#637]
運営ありがとうございます

こちらの記事を読んでいて気がつきましたが、この日本語サイトは本家の英語サイトと比べて
Compotion APIの記法でのコードの記述が少ないと感じています

https://zenn.dev/sa2knight/articles/why_react_folks_dont_choose_vue#comment-1b1bf966ea53a6

本家の英語サイトはトグルでCompotion APIとOption APIを切り替えられるのですが、
この日本語サイトはそういった機能も無いように見受けられます

ただ、SEO的にこちらの方が先に引っかかるので、逆に日本人がVue3のCompotion APIを扱う上で大きな障害になっていると感じています

このプロジェクトは活発に動いていないように見えますが、維持されていますか?
また維持されている場合は、Compotion APIの記法でのコードの記述の強化やお手伝いできることはありますか?

**Comment by kazupon** [comment]
@yogarasu 
ありがとうございます。

翻訳プロジェクトですが、維持はされています。
こちらの方で進めています。
https://github.com/vuejs-translations/docs-ja

翻訳状況ですが、こちらです。
https://github.com/vuejs-translations/docs-ja/discussions/464#discussioncomment-3060386

日本語翻訳の公開タイミングですが、ガイドが終わったら公開する予定です。
現在残り1つのみとなっている状況です。
https://github.com/vuejs-translations/docs-ja/issues/6

**Comment by ghost** [comment]
@kazupon 
教えてくださってありがとうございます

今の既存サイトは情報が古く、ドメインそのまま近々そちらのプロジェクトの内容にドキュメントが置き換わる認識でよかったでしょうか?

**Comment by kazupon** [comment]
@yogarasu 
はい。
https://jp.vuejs.org/ でホストする予定です。

**Comment by kazupon** [comment]
ガイド(Guide)部分が全て終わったら公開しますが、こちらのissueのトップにピン留めされているissueまとめを見てもらえるとわかるかと思いますが、まだ他の部分も翻訳されていない箇所があります。
https://github.com/vuejs-translations/docs-ja/issues

Vue.js は他のフレームワークのOSSとは違い、企業ベースではないOSSです。
そういったOSSはコミュニティによるgive & takeが大事だと思っています。
もし、興味があるようでしたら、ドキュメントで OSS の contribution としていただけるとうれしいです。

**Comment by ghost** [comment]
@kazupon 
Zennの方でも言及してくださり、ありがとうございます!

日本語ドキュメントの改訂状況を知らなかったので、色々と四苦八苦して今はVueを離れていますが、
Vue自体は好きなので、機会があればcontributeさせていただきます!
