### ISSUE TITLE
Essentials > Event Handling の翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#9]
Epic: #1

## About

https://v3.vuejs.org/guide/events.html の翻訳をお願いします。

## Goal

https://v3.vuejs.org/guide/events.html の翻訳が全てなされていること

## Note

翻訳ガイドラインは、ひとまず v2 のものに完全に遵守することとします。
https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md

**Comment by entaku19890818** [comment]
@potato4d こちら翻訳させてください！

**Comment by potato4d** [comment]
@entaku19890818 よろしくお願いいたします！

**Comment by entaku0818** [comment]
v2で該当するのはここのページなので、翻訳の参考にする
https://jp.vuejs.org/v2/guide/events.html
